FROM php:7.1-fpm

### 设置代理
# ENV http_proxy http://docker.for.mac.localhost:1080
# ENV https_proxy http://docker.for.mac.localhost:1080

COPY ./php.ini /usr/local/etc/php/

RUN apt-get update && apt-get install -y libssl-dev pkg-config \
    && pecl install redis \
    && pecl install xdebug \
    && pecl install mongodb \
    && docker-php-ext-enable redis xdebug mongodb
